(() => {
  "use strict";
  const $ = (id) => document.getElementById(id);
  const ui = { flight: document.querySelector(".flight"), balance: $("balance"), bets: $("bets"), targets: $("targets"), targetPayout: $("targetPayout"), launch: $("launch"), multiplier: $("multiplier"), state: $("state"), result: $("result") };
  let session; let bets = []; let targets = []; let betIndex = 0; let targetIndex = 0; let wallet = 0; let busy = false;
  const fmt = (value) => Number(value || 0).toLocaleString("en-US", { maximumFractionDigits: 2 });
  const say = (text, error = false) => { ui.result.textContent = text; ui.result.classList.toggle("error", error); };
  const bet = () => bets[betIndex]; const target = () => targets[targetIndex];
  function sound(frequency, duration) { try { const Ctx = window.AudioContext || window.webkitAudioContext; const ctx = window.__crashAudio || (window.__crashAudio = new Ctx()); const osc = ctx.createOscillator(); const gain = ctx.createGain(); osc.type = "sawtooth"; osc.frequency.setValueAtTime(frequency, ctx.currentTime); gain.gain.setValueAtTime(.035, ctx.currentTime); gain.gain.exponentialRampToValueAtTime(.001, ctx.currentTime + duration); osc.connect(gain).connect(ctx.destination); osc.start(); osc.stop(ctx.currentTime + duration); } catch { /* Audio is optional. */ } }
  function showWallet(next) { if (!next) return; wallet = Number(next.totalCredits) || 0; ui.balance.textContent = fmt(wallet); }
  function option(label, selected, onClick) { const button = document.createElement("button"); button.type = "button"; button.textContent = label; button.classList.toggle("selected", selected); button.disabled = busy; button.addEventListener("click", onClick); return button; }
  function renderChoices() { ui.bets.replaceChildren(...bets.map((value, index) => option(fmt(value), index === betIndex, () => { if (!busy) { betIndex = index; sound(360,.06); sync(); } }))); ui.targets.replaceChildren(...targets.map((value, index) => option(`${fmt(value)}×`, index === targetIndex, () => { if (!busy) { targetIndex = index; sound(470,.06); sync(); } }))); }
  function sync() { ui.launch.disabled = busy || !session; ui.targetPayout.textContent = bets.length ? fmt(bet() * target()) : "—"; renderChoices(); }
  function animateTo(value) { return new Promise((resolve) => { const end = Math.max(1, Number(value) || 1); const duration = Math.min(2300, 700 + end * 125); const start = performance.now(); const tick = (now) => { const p = Math.min(1,(now - start)/duration); const shown = 1 + (end - 1) * (1 - (1 - p) ** 2.35); ui.multiplier.textContent = `${shown.toFixed(2)}×`; if (p < 1) requestAnimationFrame(tick); else resolve(); }; requestAnimationFrame(tick); }); }
  async function launch() { if (busy || !session) return; if (bet() > wallet) { say("Insufficient credits for this bet.", true); return; } busy = true; ui.flight.classList.remove("busted", "cashed"); ui.flight.classList.add("running"); ui.state.textContent = "IN FLIGHT"; ui.multiplier.textContent = "1.00×"; say(`Rocket launched — target ${fmt(target())}×.`); sync(); sound(150,.15); let round; try { round = await Gamish.play({ bet: bet(), target: target() }); } catch (error) { busy = false; ui.flight.classList.remove("running"); ui.state.textContent = "READY TO LAUNCH"; say(error?.code === "insufficient_credits" ? "Insufficient credits for this bet." : "Launch could not start. Try again.", true); sync(); return; } await animateTo(round.outcome === "win" ? round.multiplier : round.value); ui.flight.classList.remove("running"); if (round.outcome === "win") { ui.flight.classList.add("cashed"); ui.state.textContent = "CASHED OUT"; say(`Cashed out at ${fmt(round.multiplier)}× — won ${fmt(round.payout)}.`); sound(760,.25); } else { ui.flight.classList.add("busted"); ui.state.textContent = "CRASHED"; say(`Crashed at ${fmt(round.value)}× — the rocket missed ${fmt(target())}×.`); sound(85,.35); } Gamish.track("round_shown", { outcome: round.outcome, target: target(), value: round.value }); busy = false; sync(); }
  ui.launch.addEventListener("click", launch); sync();
  (async () => { try { session = await Gamish.connect(); bets = session.math.bets.slice(); targets = session.math.targets.slice(); showWallet(session.wallet); Gamish.onWallet(showWallet); say(session.preview ? "Preview mode — choose a target and launch." : "Choose a cash-out target, then launch."); } catch { say("Could not connect — please reopen the game.", true); } sync(); })();
})();
