// Game catalogue tool.
//   node scripts/games.mjs              validate every game and regenerate the catalogue
//   node scripts/games.mjs --check      fail if a game is invalid or the generated files are stale
//   node scripts/games.mjs new <id> [Title] [Category]   start a new game from games/_template
import { cp, readdir, readFile, stat, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { publicMath, validateMath } from "../lib/game-models.js";

const ROOT = new URL("..", import.meta.url).pathname;
const GAMES_DIR = join(ROOT, "games");
const CATALOG = join(GAMES_DIR, "catalog.json");
const SERVER_MATH = join(ROOT, "lib", "games.generated.js");
const CATEGORIES = ["Slots", "Instant", "Cards", "Table Games", "Numbers", "Arcade", "Quick Games"];

const exists = (path) => stat(path).then(() => true, () => false);
const readJson = async (path) => {
  try {
    return JSON.parse(await readFile(path, "utf8"));
  } catch (error) {
    throw new Error(`${path.replace(ROOT, "")}: ${error.code === "ENOENT" ? "missing" : error.message}`);
  }
};

async function loadGame(id) {
  const dir = join(GAMES_DIR, id);
  const manifest = await readJson(join(dir, "game.json"));
  const math = await readJson(join(dir, "math.json"));
  const problem = (message) => { throw new Error(`games/${id}/game.json: ${message}`); };
  if (manifest.id !== id) problem(`"id" must be "${id}" (the folder name)`);
  if (typeof manifest.title !== "string" || manifest.title.length < 2 || manifest.title.length > 40) problem("\"title\" must be 2 to 40 characters");
  if (!CATEGORIES.includes(manifest.category)) problem(`"category" must be one of: ${CATEGORIES.join(", ")}`);
  if (!/^\d+\.\d+\.\d+$/.test(manifest.version ?? "")) problem("\"version\" must look like 1.0.0");
  if (!["module", "builtin"].includes(manifest.runtime)) problem("\"runtime\" must be \"module\" (its own folder) or \"builtin\"");
  if (manifest.accent && !/^#[0-9a-f]{6}$/i.test(manifest.accent)) problem("\"accent\" must be a colour like #ffc14f");
  if (manifest.runtime === "module") {
    if (!manifest.entry || !(await exists(join(dir, manifest.entry)))) problem(`"entry" file ${manifest.entry ?? "(none)"} not found`);
  }
  if (manifest.cover && !(await exists(join(dir, manifest.cover)))) problem(`"cover" file ${manifest.cover} not found`);
  const figures = validateMath(id, math);
  return {
    math,
    figures,
    entry: {
      id,
      title: manifest.title,
      category: manifest.category,
      version: manifest.version,
      runtime: manifest.runtime,
      url: manifest.runtime === "module" ? `/games/${id}/${manifest.entry}` : null,
      cover: manifest.cover ? `/games/${id}/${manifest.cover}` : null,
      description: manifest.description ?? "",
      accent: manifest.accent ?? "#ffc96b",
      math: publicMath(math, figures),
    },
  };
}

async function build() {
  const ids = (await readdir(GAMES_DIR, { withFileTypes: true }))
    .filter((entry) => entry.isDirectory() && !entry.name.startsWith("_") && !entry.name.startsWith("."))
    .map((entry) => entry.name)
    .sort();
  const games = [];
  for (const id of ids) games.push(await loadGame(id));
  const catalog = `${JSON.stringify({ games: games.map((game) => game.entry) }, null, 2)}\n`;
  const serverMath = `// Generated by scripts/games.mjs from games/*/math.json. Do not edit; run \`npm run games\`.\n`
    + `export const GAME_MATH = ${JSON.stringify(Object.fromEntries(games.map((game) => [game.entry.id, game.math])), null, 2)};\n\n`
    + `export const GAME_INFO = ${JSON.stringify(Object.fromEntries(games.map(({ entry }) => [entry.id, { title: entry.title, category: entry.category, runtime: entry.runtime }])), null, 2)};\n`;
  return { games, catalog, serverMath };
}

async function newGame(id, title = id.replace(/-/g, " ").replace(/\b\w/g, (c) => c.toUpperCase()), category = "Quick Games") {
  if (!/^[a-z0-9][a-z0-9-]{1,39}$/.test(id ?? "")) throw new Error("Usage: npm run game:new -- <id> [Title] [Category]   (id: lowercase, digits, dashes)");
  const dir = join(GAMES_DIR, id);
  if (await exists(dir)) throw new Error(`games/${id} already exists`);
  await cp(join(GAMES_DIR, "_template"), dir, { recursive: true });
  const manifestPath = join(dir, "game.json");
  const manifest = await readJson(manifestPath);
  Object.assign(manifest, { id, title, category });
  await writeFile(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`);
  const htmlPath = join(dir, "index.html");
  await writeFile(htmlPath, (await readFile(htmlPath, "utf8")).replaceAll("Template Game", title));
  console.log(`Created games/${id}. Design it, tune games/${id}/math.json, then run: npm run games`);
}

const [command, ...args] = process.argv.slice(2);
try {
  if (command === "new") {
    await newGame(...args);
    process.argv = [];
  }
  const { games, catalog, serverMath } = await build();
  if (command === "--check") {
    const stale = [];
    if ((await readFile(CATALOG, "utf8").catch(() => "")) !== catalog) stale.push("games/catalog.json");
    if ((await readFile(SERVER_MATH, "utf8").catch(() => "")) !== serverMath) stale.push("lib/games.generated.js");
    if (stale.length) throw new Error(`${stale.join(" and ")} out of date: run npm run games`);
  } else {
    await writeFile(CATALOG, catalog);
    await writeFile(SERVER_MATH, serverMath);
  }
  for (const { entry, figures } of games) {
    console.log(`${entry.id.padEnd(16)} ${entry.runtime.padEnd(8)} RTP ${(figures.rtp * 100).toFixed(2)}%  hit ${(figures.hitRate * 100).toFixed(1)}%  max ${figures.maxMultiplier}×`);
  }
} catch (error) {
  console.error(error.message);
  process.exit(1);
}
